const data = {
    products: [
      {
        name: 'Nike Slim shirt',
        slug: 'nike-slim-shirt',       
        category: 'Trending',
        link: "/trending",
        image: '/images/men1.jpg', // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        name: 'Adidas Fit Shirt',
        slug: 'adidas-fit-shirt',       
        category: 'Seasonal',
        link: "/seasonal",
        image: '/images/women5a.jpg',
        price: 250,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'Nike Slim Pant',
        slug: 'nike-slim-pant',        
        category: 'Sales',
        link: "/sales",
        image: '/images/kids1a.jpg',
        price: 25,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      // {
      //   name: 'Adidas Fit Pant',
      //   slug: 'adidas-fit-pant',
      //   category: 'Pants',
      //   image: '/images/',
      //   price: 65,
      //   countInStock: 5,
      //   brand: 'Puma',
      //   rating: 4.5,
      //   numReviews: 10,
      //   description: 'high quality product',
      // },
    ],
  };
  export default data